content/docs/developer/testing/index.md
Currently, the reader is instructed to copy from the browser a new Resources Config file. However the shown outputs from `kubectl` list the service name from the file from the repo, not the file from the guide. Since the guide assumes the user is in the root directory of the project anyways (e.g. with mirrord-agent/Dockerfile), let's use the files from the project. This way, the reader does not have to copy files from the browser, and the output they see in the guide matches the output they get on their system.
=> Use files from repo in tests guide

content/docs/reference/env/index.md
refer: https://github.com/metalbear-co/mirrord/pull/189, closes https://github.com/metalbear-co/mirrord/issues/338
=> Fix explanation of how env is set

content/docs/reference/env/index.md, content/docs/reference/fileops/index.md
https://github.com/metalbear-co/mirrord/issues/372
=> Adapt docs to new conf.

content/docs/overview/quick-start.md
update "mirrord can be used in two ways" -> "mirrord can be used in three ways"
=> Small update to Quick Start

content/docs/overview/real-world-example.md
Debugging an Application with mirrord .feat NextJS
=> Example: Debugging an Application with mirrord

content/docs/reference/traffic/index.md
Should only be merged once https://github.com/metalbear-co/mirrord/pull/843 is merged and released.
=> Add HTTP Header Filter documentation.

content/docs/overview/real-world-example.md, content/docs/reference/fileops/index.md
https://github.com/metalbear-co/mirrord/issues/1174
=> remove --no-fs

content/docs/reference/targets/index.md
Add target reference, also explain targetless mode. #72.
=> Add target reference - #72

layouts/partials/sections/section-waitlist.html
=> Improve waitlist join alert

content/docs/overview/configuration.md
- Issue: #69 
- Update accordingly to [#1577](https://github.com/metalbear-co/mirrord/pull/1577)
=> Update configuration.md with latest auto-generated docs.

content/feedback/_index.md, layouts/feedback/list.html
Add /feedback page to redirect to google forms for feedback
=> Add /feedback redirect

content/docs/overview/quick-start.md
Remove an extraneous backquote
=> docs: remove extraneous backquote

assets/css/site.css, layouts/partials/sidebar/docs-toc.html
=> Make the sidebar scrollable

content/docs/overview/faq.md
Feel free to add commits to this branch if you want to.
=> Add FAQ: lingering agent pods.

content/docs/overview/faq.md
Related to https://github.com/metalbear-co/mirrord/issues/1921
=> Add alternative solution for go binaries

content/docs/overview/third-party/index.md
add "Advanced Kubernetes Debugging Techinques" slides to third party resources
=> add "Advanced Kubernetes Debugging Techinques" slides to third party

config/_default/menus/menus.yaml, content/pages/contact/index.md, layouts/_default/contact.html, layouts/partials/form/handle-submission.html, layouts/partials/sections/section-waitlist.html, yarn.lock
Closes #171
Everything is copied from other pages, mostly from the waitlist form. ChatGPT helped me change it.
Didn't try to design it a lot, let me know if there is a different design you want for the form.
Todo: setup a backend endpoint for the form.
=> Contact us form

content/docs/overview/faq.md
=> Add FAQ entry on FS exceptions.

content/docs/overview/configuration.md
closes #181, and there were also a couple of other updates to the docs that didn't make it to the website yet.
=> update configuration docs

content/docs/overview/configuration.md
ran medschool, changed `lastmod` date.
=> Update configuration docs with recent changes

content/docs/overview/configuration.md
Just copied the conf docs from the mirrord repo.
Last open task in https://github.com/metalbear-co/operator/issues/405
=> Update configuration docs with copy_target fixes.

content/docs/using-mirrord/chrome-browsing, content/docs/using-mirrord/targetless.md, content/docs/using-mirrord/web-browsing.md
Following my question in discord (https://discord.com/channels/933706914808889356/950020257156833340/1201226837032976537)
and Aviram's suggestion to document a working setup  (https://github.com/metalbear-co/mirrord/issues/1944#issuecomment-1772139840) - I've created this suggestion. 
Hope It will be useful to future readers as well!
Cheers!
=> Added a suggested setup for chrome web browsing

content/docs/using-mirrord/status.md
=> add mirrord operator status docs

content/docs/managing-mirrord/security/index.md
merge after https://github.com/metalbear-co/charts/pull/52 is released
=> improve namespace role

content/docs/faq/common-issues.md
=> improve bottlerocket FAQ

content/docs/managing-mirrord/monitoring/index.md
Pending operator release + chart release.
=> add monitoring section

layouts/docs/single.html
I had fixed this earlier somewhere, found it so thought I'd push: closes #272
=> Make left sidebar sticky

content/docs/reference/configuration.md
Resolves https://github.com/metalbear-co/mirrord/issues/2508
=> Move copy_target under feature to make the complete sample json valid

layouts/partials/sections/section-hero.html
=> Add simple badge from producthunt

content/docs/managing-mirrord/monitoring/index.md
Related to https://github.com/metalbear-co/operator/issues/572
=> Added client id to mentioned log fields

content/docs/faq/limitations.md
=> Add section to limitations about static binaries

assets/css/site.css, assets/css/styles.css
=> Hide "On this page section" when empty

assets/css/site.css
=> Change narrow docs view to up to 1280px

content/docs/reference/configuration.md
I guess it hasn't been reimported since the medschool change? The diff is pretty big.
=> update configuration from mirrord repo

content/docs/faq/common-issues.md
=> change default port from 3000 to 443

content/docs/using-mirrord/queue-splitting/index.md
Case is non-conventional in first release, changed to camelCase in https://github.com/metalbear-co/mirrord/pull/2712
=> fix CRD field name case

assets/css/site.css, assets/css/styles.css, layouts/docs/single.html
Closes #317, closes #302 (for real this time)
=> Narrow screens

content/docs/managing-mirrord/policies/index.md, content/docs/managing-mirrord/security/index.md
Issue #373 
Blocking traffic mirroring added [here](https://github.com/metalbear-co/mirrord/pull/2967)
=> Updated `MirrordPolicy` doc with new mirror block feature

content/docs/managing-mirrord/policies/index.md
=> Extended policy docs

content/docs/managing-mirrord/monitoring/index.md
=> Prometheus Docs

content/docs/using-mirrord/wsl/index.md
- Issue: n.a.
Solution is based on: [discord thread](https://discordapp.com/channels/933706914808889356/1315499840427528276/1315551116204707911)
=> Troubleshooting for certificate issue in intellij wsl.

content/docs/managing-mirrord/policies/index.md
=> Adds docs to the new env policies.

content/docs/faq/general.md
Fix text links in the FAQ page.
=> Fix text links
